spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.22.0.2:3306/desafiomv
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    generate-ddl: true
